default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gamedreams_db_admin
  password: gamedreams-db-pas
  host: localhost
  port: 5433
  

development:
  <<: *default
  database: gamedreams_development


test:
  <<: *default
  database: gamedreams_test



